In [4]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

df = pd.read_csv('../../processed/features_v2.csv')

In [5]:
df.head()

,filename,classe,pixel_mean,pixel_std,lum_interieur_masque,lum_exterieur_masque,surface_masque,variance_laplacien
0,COVID-1.png,COVID,42.2313,63.8117,144.7131,10.9031,0.234125,1779.5722
1,COVID-10.png,COVID,45.0521,65.8467,140.9980,10.8718,0.262670,2205.6286
2,COVID-1000.png,COVID,42.3115,63.1703,139.1298,10.8428,0.245299,1697.4233
3,COVID-1001.png,COVID,29.9235,52.1309,139.1083,10.9089,0.148320,1661.2817
4,COVID-1002.png,COVID,65.1165,75.3402,138.8807,10.7731,0.424201,2473.2551

In [7]:
data = wine.drop(['filename','classe'], axis = 1)
target = wine['classe']

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=42)

In [9]:
scaler = preprocessing.StandardScaler().fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
parametres = {'C':[0.1,1,10], 'kernel':['rbf','linear', 'poly'], 'gamma':[0.001, 0.1, 0.5]}
clf = svm.SVC()
grid_clf = model_selection.GridSearchCV(estimator=clf, param_grid=parametres)
grille = grid_clf.fit(X_train_scaled,y_train)

print(pd.DataFrame.from_dict(grille.cv_results_).loc[:,['params', 'mean_test_score']])

                                            params  mean_test_score
0      {'C': 0.1, 'gamma': 0.001, 'kernel': 'rbf'}         0.507919
1   {'C': 0.1, 'gamma': 0.001, 'kernel': 'linear'}         0.658628
2     {'C': 0.1, 'gamma': 0.001, 'kernel': 'poly'}         0.485601
3        {'C': 0.1, 'gamma': 0.1, 'kernel': 'rbf'}         0.651068
4     {'C': 0.1, 'gamma': 0.1, 'kernel': 'linear'}         0.658628
5       {'C': 0.1, 'gamma': 0.1, 'kernel': 'poly'}         0.588673
6        {'C': 0.1, 'gamma': 0.5, 'kernel': 'rbf'}         0.652449
7     {'C': 0.1, 'gamma': 0.5, 'kernel': 'linear'}         0.658628
8       {'C': 0.1, 'gamma': 0.5, 'kernel': 'poly'}         0.629050
9        {'C': 1, 'gamma': 0.001, 'kernel': 'rbf'}         0.646089
10    {'C': 1, 'gamma': 0.001, 'kernel': 'linear'}         0.658628
11      {'C': 1, 'gamma': 0.001, 'kernel': 'poly'}         0.485601
12         {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}         0.660488
13      {'C': 1, 'gamma': 0.1, 'kernel': 'linear'}         0.658628
14        {'C': 1, 'gamma': 0.1, 'kernel': 'poly'}         0.614351
15         {'C': 1, 'gamma': 0.5, 'kernel': 'rbf'}         0.662888
16      {'C': 1, 'gamma': 0.5, 'kernel': 'linear'}         0.658628
17        {'C': 1, 'gamma': 0.5, 'kernel': 'poly'}         0.634570
18      {'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}         0.657368
19   {'C': 10, 'gamma': 0.001, 'kernel': 'linear'}         0.657548
20     {'C': 10, 'gamma': 0.001, 'kernel': 'poly'}         0.485601
21        {'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}         0.665827
22     {'C': 10, 'gamma': 0.1, 'kernel': 'linear'}         0.657548
23       {'C': 10, 'gamma': 0.1, 'kernel': 'poly'}         0.629290
24        {'C': 10, 'gamma': 0.5, 'kernel': 'rbf'}         0.668107
25     {'C': 10, 'gamma': 0.5, 'kernel': 'linear'}         0.657548
26       {'C': 10, 'gamma': 0.5, 'kernel': 'poly'}         0.636550

In [12]:
print(grid_clf.best_params_)

{'C': 10, 'gamma': 0.5, 'kernel': 'rbf'}

In [13]:
#Prédiction des features test et création de la matrice de confusion
y_pred = grid_clf.predict(X_test_scaled)
pd.crosstab(y_test, y_pred, rownames=['Classe réelle'], colnames=['Classe prédite'])

Classe prédite   COVID  Lung_Opacity  Normal  Viral Pneumonia
Classe réelle
COVID               34           243     360                2
Lung_Opacity        12           661     531                2
Normal              13           153    1873                3
Viral Pneumonia      0             1       8              271

In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

                 precision    recall  f1-score   support

          COVID       0.58      0.05      0.10       639
   Lung_Opacity       0.62      0.55      0.58      1206
         Normal       0.68      0.92      0.78      2042
Viral Pneumonia       0.97      0.97      0.97       280

       accuracy                           0.68      4167
      macro avg       0.71      0.62      0.61      4167
   weighted avg       0.67      0.68      0.63      4167